#####################
##### AUTOSTART #####
#####################

exec-once = swww-daemon                         # Wallpaper daemon 
exec-once = mako                                # Notification daemon
exec-once = tlp                                 # powersaver
exec-once = tlp power-saver                 # enable powersaver (redundant/just in case)
exec-once = hyprlauncher -d                     # Hyprlauncher/Menu daemon
exec-once = ~/.local/bin/battery_monitor.sh     # Low Battery Warning script
exec-once = ~/.local/bin/charge_status.sh       # Bash Script to Notify Charger plugging and removal
