#Monitor config for Omarchy Setup
#
#Environment/Zoom scale for GDK based GUIs
#env = GDK_SCALE,1

#For Thinkbook 14 in-built monitor
monitor = eDP-1, 1920x1200, 0x0, 1.2

#For Old Dell Monitor\
monitor = HDMI-A-2, 1366x768@60,auto,1

#For Home Smart TV
#monitor = HDMI-A-1, 4096x2160@60, 1920x0, 2
