  #Overrides for the defaul keybinds of base Omarchy
  

#Unbinding useless/to-be-changed keybinds
unbind = SUPER SHIFT, M                   #Open Spotify
unbind = SUPER SHIFT, G                   #Open Signal
unbind = SUPER SHIFT, slash               #Open 1password
unbind = SUPER SHIFT ALT, A               #Open Grok
unbind = SUPER SHIFT ALT, G               #Open Whatsapp
unbind = SUPER SHIFT ALT, X               #Open X with post
unbind = SUPER SHIFT CTRL, G              #Open Google Messages
unbind = SUPER SHIFT, X                   #Open Webapp with "X.com"
unbind = SUPER SHIFT, B                   #Open default browser
unbind = SUPER SHIFT ALT, B               #Just in case 


#New bindings
bind = SUPER SHIFT, E, exec, $terminal -e yazi                                                  #Open yazi
bind = SUPER SHIFT, V, exec, code                                                               #Open VScode
bind = SUPER SHIFT, Z, exec, omarchy-launch-or-focus-webapp "https://web.whatsapp.com"          #Open Whatsapp
bind = SUPER SHIFT, P, exec, omarchy-launch-webapp "https://perplexity.ai"                      #Open perplexity
bind = SUPER SHIFT, W, exec, $terminal -e nmtui                                                 #Open NetworkManager TUI  
bind = SUPER SHIFT, B, exec, brave                                                              #Open Brave browser 
bind = SUPER SHIFT ALT, B, exec, B, exec, brave                                                 #Open Brave browser 
bind = SUPER SHIFT ALT, B, exec, $browser                                                       #Open Default browser
bind = SUPER CTRL, M, exec, missioncenter                                                       #Open Mission-Center
bind = SUPER CTRL, C, exec, gnome-calculator                                                    #Open Calculator  
bind = SUPER CTRL, O, exec, desktopeditors                                                      #Open Onlyoffice
bind = SUPER, B, exec, $terminal -e w3m duckduckgo.com                                          #Open w3m with search engine(Duckduckgo)

