########################
##### KITTY CONFIG #####
########################


allow_remote_control no

font_family     "JetBrainsMonoNL Nerd Font Medium"
bold_font	auto
italic_font	auto
bold_italic_font	auto
font_size	10.7


background_opacity  1
background_blur     0
background #111111
dynamic_background_opacity no

osc_color_override no


editor nvim

window_padding_width	4
confirm_os_window_close	0

sync_to_monitor	yes
